apiVersion: ENC[AES256_GCM,data:YUw=,iv:B36hxdt6lxt6ZOSYWwa6Yy0VzmI2pjbsknOFRENgZfY=,tag:ah5VA90UzmjflEEPlVkiCw==,type:str]
kind: ENC[AES256_GCM,data:NNfqHBM0,iv:vyJhQL8Yr6CU6R8ukosd+BxnB5AgsP7rKx71tsUXIQk=,tag:dPc5NYo/gNE9fRBrkMdmzw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YYVIKnU7rzMg2OW+vobh,iv:87FJiS/bUquN1k0I4NnQaifS2X0KhcCov5kiSKruT/o=,tag:FUSUI+jwPG6SaggmHfXgKQ==,type:str]
    namespace: ENC[AES256_GCM,data:sIiPdcQcb7U=,iv:UNXECaf7YLy50zC/NMrx8kI7OZE1lQ4SfaWk8pG37Q0=,tag:ARrFZF1uADnxnVu7pub80A==,type:str]
data:
    admin-password: ENC[AES256_GCM,data:ozkuEmnR4G0=,iv:tg8k47toG3K7jtyD8g3HMcIaJl6gJWJ8UYHrpli6EDA=,tag:Xi6ngreV7Jm9IOIsn5TIDg==,type:str]
sops:
    age:
        - recipient: age15xkpdtjhalua0x9lg8r5g4kaue2hjphq5r8mpsun7n6445ks84psqhz9ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ0xMeGZ6QlpCRWtENGd3
            Uk0rUUhBc2hmbnVOYUUxQ0JkTHczZk9HZ3dJCmQ0Q2V1SUpZdTJzenlFWWRZMjZk
            QlRreHAwNHM2bEJlU1c4K2Yvd3phRk0KLS0tIFVPbzc3ZjRzS2JRZkY4Um9QRTAy
            b3RNSEZwcTJGL3h0MTZhZTVCdlo2bkEKaWzCLGVbY7+r2UL+Rw5BzmCEUmdrQ7+0
            aHPpwxsi8L2z6xwYIMgf/WbAvVMbYUOJAy4do8aU028gqG5OgJqV0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jyklxpn59trjjkd5tw3ryv2wwqq4matk7amhtswdfhvces88cprs48v2hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTGhIbjNaRDFMNFdHc3Rw
            emlnQnY3dXFKeHR1eVB3TmNKZTRrZzJURUNVCnd2Ti9yNmFSTkc4WTZSQzBUaEl5
            ZTdwS0R0U3VxYkJXTS93V0EwQlZtYm8KLS0tIFVVeGRESE9sRlZBMGRoR29mdFNi
            eE5XRHpMSDFnZ3dKVXYwazNpa2pyMHMKWRpWfV3kCJn4nqI+tPeiSgI8vwH63YKE
            zulkU5QyI52OmA80hvxx90AfQoZ+Yd4J32xISbTOaigY5u4fkm9/Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T09:52:22Z"
    mac: ENC[AES256_GCM,data:gfBeODRISeCnO2l+YMnroRF/bY53StrrzsM8dLL68KA3XXU0NA4hw9hpoStQpqUiMs3Nc+CWNvGq80qT210jOX4IHhB8OM4VDGPcLueeBgHG9dYiSGYlRRFxcTlmWaoGx5/JQC8QbZ3jLlpHbL6pKurSAgV2p93aIJ/fthatJwg=,iv:9X8NQ7+VTmwr80PzVrg9xzFgNtAkWQCT28FcXlf9IDI=,tag:zSshBqPTqhq3fpGsgK3mVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
