apiVersion: v1
kind: Pod
metadata:
  name: postgres-init
  namespace: postgres
spec:
  restartPolicy: Never
  containers:
    - name: init
      image: postgres:18.1
      command:
        - "sh"
        - "-c"
        - |
          until pg_isready -h postgres-svc.postgres -U $PG_USERNAME -d $PG_DATABASE; do sleep 2; done
          for f in /sql/*.sql; do
            psql -v ON_ERROR_STOP=1 -h postgres-svc.postgres -U $PG_USERNAME -d $PG_DATABASE -f "$f"
          done
      env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: admin-password
        - name: PG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-cm
              key: POSTGRES_DB
        - name: PG_USERNAME
          valueFrom:
            configMapKeyRef:
              name: postgres-cm
              key: POSTGRES_USER
      volumeMounts:
        - name: sql
          mountPath: /sql
  volumes:
    - name: sql
      configMap:
        name: postgres-init-sql
