apiVersion: ENC[AES256_GCM,data:wJo=,iv:Oxnfyf4EP7Y61K3d7lM/OSW6efl+zY8ggo+nmlwHols=,tag:u0uFT+BOgB/YTeD1jX+ykA==,type:str]
kind: ENC[AES256_GCM,data:Oq4FCKt7,iv:FXnoZ/uOvPHNdlzag8ESUYsUvdLmENGvLw+NVauK3bo=,tag:wjHeEZf/OOreJqRonXXCbA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:A6N+z2lT8KvM97F/0MI=,iv:SO9PkRhdgg3ZnnersXpjAT995LOkrGKQBkPFwW2yDh4=,tag:BdCuYPb+yrNSEmSxSMLumw==,type:str]
    namespace: ENC[AES256_GCM,data:QwfTPydClQ==,iv:jkY3uJaTckWbTGP8xrEaeBmndGk1VDlFO8NaNgEJ8oE=,tag:bt8/df7Sg6XVkrvYvbIY5Q==,type:str]
type: ENC[AES256_GCM,data:36asQ4YX,iv:G2i9kCLqg1KNHZ4PPudoKKx2F2u0MDoLMgxcz8MS528=,tag:E2URIQWf+cYW6vEb9DIBAw==,type:str]
data:
    db_password: ENC[AES256_GCM,data:6ofHpz8KkgOUBt4LY1NJtA==,iv:AFFJ8ImOo5Bdt2oER/f0i8ccMyePeK8LX6/hew367vY=,tag:007imQFCRXHOuhWqHjjVkA==,type:str]
sops:
    age:
        - recipient: age15xkpdtjhalua0x9lg8r5g4kaue2hjphq5r8mpsun7n6445ks84psqhz9ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Z1duYWcvbDg0T0JCdm9Q
            eG9wZlV2OEVOZVp3QXdXa2Q1Yk5CQ0dqdVZRCk45bGkrTkZHS3c2M1VJd0JOMUo1
            V29jM1ZtTDFqMDIwWjg3dGlycEVPYU0KLS0tIGg1S0x3RTF3bWc1T3ZiOGpWN3gz
            MGNzdk9DVGNWZXpIQzkrZ0FjWGRpMHMKiWdI2jrh7/M04Ftfk7lh9b9ao2q4x6k6
            sb7EAVQBB9sGl8DwmEF1kMvDAkuxopsUQJVw8sQSxqOREQusGDQlEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jyklxpn59trjjkd5tw3ryv2wwqq4matk7amhtswdfhvces88cprs48v2hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM3llNE5aRDRUczJCRUpZ
            NHp3MjEyclZROW5zUTlJNElTMjhldEorTlVFCmJ6R0ZwTWNpdGFDQ3pSRHVYSE1O
            UjVXQVBHMW9OOFJVcjE0MStxczNZUmsKLS0tIHV1OUp4VWN3L0ZpODVWby8xbCta
            Y0Qzd2NVYU4xOGpnTEZXenlYeXpVaEEKRIO8GRNt7bEfjhny8vW9Qyrt9frXYa8Q
            E3Yuh4bz3u2ehAOzp7yQqAhdGcFG/oyhspMexAx5pB4WWDHLqlHykQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T10:23:11Z"
    mac: ENC[AES256_GCM,data:JEPJUK1H2Vj0CA60nA8EkupGllcbwwqpKvI1cv8vrz3nXEbeblQdf+tMy6ta1Qf6o6tJmcqwh2kbko+vM7fDknx2iyrALcM+pwAI1ADTFmH/aqzbTPAprFG15co7E3mqQ19QdZaJIdUyPhYK5tR2r8jPir2K1xWBLGdozAXgLwI=,iv:pXpaLR1barbJgMsnjZMaxFl1dLFy4BsXGBUo07iek1o=,tag:ao9N7vGVSH1I6y+Uv1XyMA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
