apiVersion: v1
kind: Pod
metadata:
  name: db-create-tables-task
  namespace: project
spec:
  containers:
    - name: db-create-tables-job
      image: postgres:18.1
      imagePullPolicy: IfNotPresent
      command:
        - "sh"
        - "-c"
        - |
          until pg_isready -h postgres-svc.postgres -U $USERNAME -d $DATABASE; do sleep 2; done
          for f in /sql/*.sql; do
            psql -v ON_ERROR_STOP=1 -h postgres-svc.postgres -U $USERNAME -d $DATABASE -f "$f"
          done
      env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: cutlass-secret
              key: db_password
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: cutlass-config
              key: db_username
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: cutlass-config
              key: db_name
      volumeMounts:
        - mountPath: /sql
          name: sql
  restartPolicy: Never
  volumes:
    - name: sql
      configMap:
        name: db-create-tables-sqls
